services:
  cassandra:
    image: cassandra:5.0
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: url-shortener-local
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 20
