{{- if include "url-shortener.cassandraSSLSecretEnabled" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.cassandraSSLSecretName" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cassandra.sslCA }}
  ca.crt: {{ .Values.cassandra.sslCA | b64enc | quote }}
  {{- end }}
  {{- if .Values.cassandra.sslCert }}
  tls.crt: {{ .Values.cassandra.sslCert | b64enc | quote }}
  {{- end }}
  {{- if .Values.cassandra.sslKey }}
  tls.key: {{ .Values.cassandra.sslKey | b64enc | quote }}
  {{- end }}
{{- end }}
