{{- if .Values.cassandra.valsSecret.enabled }}
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: {{ printf "%s-cassandra-vals" (include "url-shortener.fullname" .) }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    {{- with .Values.cassandra.valsSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with (default (printf "%s-cassandra" (include "url-shortener.fullname" .)) .Values.cassandra.valsSecret.name) }}
  name: {{ . }}
  {{- end }}
  ttl: {{ .Values.cassandra.valsSecret.ttl }}
  type: Opaque
  data:
    {{- range $key, $val := .Values.cassandra.valsSecret.data }}
    {{- if $val.ref }}
    {{ $key }}:
      ref: {{ $val.ref | quote }}
      encoding: {{ $val.encoding | default "text" }}
    {{- end }}
    {{- end }}
---
{{- end }}
{{- if .Values.cassandra.valsSSLSecret.enabled }}
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: {{ printf "%s-cassandra-ssl-vals" (include "url-shortener.fullname" .) }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    {{- with .Values.cassandra.valsSSLSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with (default (printf "%s-cassandra-ssl" (include "url-shortener.fullname" .)) .Values.cassandra.valsSSLSecret.name) }}
  name: {{ . }}
  {{- end }}
  ttl: {{ .Values.cassandra.valsSSLSecret.ttl }}
  type: Opaque
  data:
    {{- range $key, $val := .Values.cassandra.valsSSLSecret.data }}
    {{- if $val.ref }}
    {{ $key }}:
      ref: {{ $val.ref | quote }}
      encoding: {{ $val.encoding | default "text" }}
    {{- end }}
    {{- end }}
{{- end }}
