apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-shortener.fullname" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "url-shortener.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "url-shortener.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "url-shortener.configmapData" . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "url-shortener.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "url-shortener.fullname" . }}
          env:
            {{- if or .Values.session.existingSecret .Values.session.secret }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "url-shortener.sessionSecretName" . }}
                  key: SESSION_SECRET
            {{- end }}
            {{- if or .Values.cassandra.existingSecret .Values.cassandra.password }}
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "url-shortener.cassandraSecretName" . }}
                  key: CASSANDRA_PASSWORD
            {{- end }}
            {{- if or .Values.saml.existingSecret .Values.saml.privateKey }}
            - name: SAML_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "url-shortener.samlSecretName" . }}
                  key: SAML_PRIVATE_KEY
            {{- end }}
            {{- if or .Values.saml.existingSecret .Values.saml.certificate }}
            - name: SAML_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: {{ include "url-shortener.samlSecretName" . }}
                  key: SAML_CERTIFICATE
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
