{{- if not .Values.session.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-session" (include "url-shortener.fullname" .) }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
data:
  SESSION_SECRET: {{ .Values.session.secret | b64enc | quote }}
---
{{- end }}
{{- if and (not .Values.cassandra.existingSecret) (not .Values.cassandra.valsSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cassandra" (include "url-shortener.fullname" .) }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
data:
  CASSANDRA_PASSWORD: {{ .Values.cassandra.password | b64enc | quote }}
---
{{- end }}
{{- if not .Values.saml.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-saml" (include "url-shortener.fullname" .) }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
data:
  SAML_PRIVATE_KEY: {{ .Values.saml.privateKey | b64enc | quote }}
  SAML_CERTIFICATE: {{ .Values.saml.certificate | b64enc | quote }}
  SAML_IDP_METADATA: {{ .Values.saml.idpMetadata | b64enc | quote }}
{{- end }}
