{{- $renderSession := and (not .Values.session.existingSecret) .Values.session.secret -}}
{{- $renderCassandra := and (not .Values.cassandra.existingSecret) .Values.cassandra.password -}}
{{- $renderSaml := and (not .Values.saml.existingSecret) (or .Values.saml.privateKey .Values.saml.certificate) -}}
{{- if or $renderSession $renderCassandra $renderSaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $renderSession }}
  SESSION_SECRET: {{ .Values.session.secret | quote }}
  {{- end }}
  {{- if $renderCassandra }}
  CASSANDRA_PASSWORD: {{ .Values.cassandra.password | quote }}
  {{- end }}
  {{- if $renderSaml }}
  {{- if .Values.saml.privateKey }}
  SAML_PRIVATE_KEY: {{ .Values.saml.privateKey | quote }}
  {{- end }}
  {{- if .Values.saml.certificate }}
  SAML_CERTIFICATE: {{ .Values.saml.certificate | quote }}
  {{- end }}
  {{- end }}
{{- end }}
